recetas = [
    {'Nombre': 'licuado_desayuno', 'Ingredientes': ['fresas', 'yogurt natural', 'estevia', 'naranja'], 'Instrucciones': 'Tomas diez fresas les añades una taza de yogurt natural, adicionas un sobre de estevia (edulcorante) y el jugo de media naranja, mezclas todo y lo licuas de 2 a 3 minutos.','img_url': 'https://dam.cocinafacil.com.mx/wp-content/uploads/2021/10/licuados-nutritivos-1170x655.jpg'},
{'Nombre': 'jambalaya_pollo', 'Ingredientes': ['jamon', 'caldo', 'pollo', 'pimienta', 'aceite oliva', 'apio', 'cebolla', 'pimenton pimiento', 'ajo', 'arroz'], 'Instrucciones': 'En una cazuela colocas 450g de jamón y 1 1/2 vasos de agua, los cocinas por minutos, mientras cortas 450g de pollo y 1 rama de apio en cubos, pasado el tiempo escurres el jamón, luego colocas 2 cucharadas de aceite de oliva y sofries el apio previamente cortado, 2 dientes de ajo y 1/4 de cebolla. Una vez sofreido, salpimentas el pollo y lo añades a la mezcla para freirlo, ya todo freido, agregas el jamón y 1 taza de arroz, después agregas 2 1/2 tazas de caldo y dejas que cueza el arroz, una vez cocido puedes servir.','img_url': 'https://canalcocina.es/medias/_cache/zoom-07604615756ee7f8991f59610188c6da-920-518.jpg'},
{'Nombre': 'latte_calabaza', 'Ingredientes': ['puren calabaza', 'estevia', 'canela', 'jengibre', 'nuez moscada', 'leche', 'cafe', 'nata'], 'Instrucciones': '''Para el jarabe de vainilla, coloca en una olla los ingredientes y mueve constantemente hasta que el azúcar se diluya. Retira el jarabe del fuego y deja enfriar por completo, conserva el jarabe en un frasco cerrado hasta por 1 mes.
Prepara el jarabe de calabaza colocando todos los ingredientes en una olla a fuego medio. Mueve constantemente hasta que la mezcla espese ligeramente. Cuela el jarabe para retirar la pulpa de calabaza, deja enfriar y conserva en un frasco cerrado hasta por 2 semanas.
Agrega 1 cdta del jarabe de vainilla a la Leche Entera Santa Clara® y 1 ½ cda del jarabe de calabaza.
Calienta la Leche Entera Santa Clara® en el microondas por 1minuto. Vierte la leche sobre 2 shots de espresso. Agrega la crema chantilly y espolvorea la mezcla de especias encima (canela, nuez moscada, jengibre, pimienta).''','img_url': 'https://s1.eestatic.com/2020/09/07/cocinillas/recetas/bebidas/cafe-leche-especias_518959689_159383789_1706x960.jpg'},
{'Nombre': 'Carapulca chinchana', 'Ingredientes': ['fideos', 'pollo', 'ajo molido', 'cebolla', 'comino', 'achiote molido', 'tomate', 'albahaca', 'perejil', 'aceite', 'cerdo', 'papa', 'ají', 'pimienta', 'yuca'], 'Instrucciones': ''' Para la carapulcra: Paso 1: escoge la olla en la cual quieres preparar esta receta y empieza a freír el chancho. Una vez cocido retíralo a un plato y pon, en ese mismo aceite, a freír cebolla y ajo, cuando estén bien dorados incorpora los ajíes y la papa seca, siempre moviendo bien para que no se pequen ni quemen.

Paso 2: cubre este sofrito por completo con bastante agua hirviendo, echa sal y pimienta, mezcla todo y verifica la sazón. Coloca encima de todo el chancho que reservaste, tapa la olla y deja cocinar. Si usas una olla a presión serán 45min, pero si es convencional van a ser unos 60min.

Paso 3: Pasado este tiempo, saca las presas, coloca el maní molido, mueve la mezcla, agrega más agua si es necesario y verifica la sal. Deja cocinar por 10min más.
Para la sopa seca: Paso 1: preparar un aderezo a base de cebolla picada, ajo molido, ají amarillo, ají panca en una olla con aceite. Luego, añadir tomate triturado, albahaca y culantro picados, sal, pimienta, comino y achiote. Coloca la panceta de cerdo en trozos y el vino.

Paso 2: cubre este primer guiso con agua o caldo, añade los pallares crudos y deja cocinar por unos 15min, o hasta que la panceta esté suave.

Paso 3: cuando reduzca el líquido, echa los tallarines crudo con un poco de albahaca picada y un ají en tiras delgadas, mueve todo de nuevo y déjalo cocinar hasta que se seque.''','img_url': 'https://lascomidasperuanas.com/wp-content/uploads/2021/02/Receta-de-Carapulcra-chinchana.jpg'},
{'Nombre': 'Olluquitos con carne', 'Ingredientes': ['ollucos', 'carne', 'ají mirasol', 'cebolla', 'aceite', 'ajo', 'oregano', 'sal', ' pimienta'], 'Instrucciones': '''1.  Cortar la carne en cubos pequeños. Pelar la papa amarilla y cortarlas en 8 pedazos iguales. Cortar la cebolla en cubitos pequeños.

2.  Calentar el aceite en una olla y freír la cebolla. Agregar el ajo, el ají panca, un cubo MAGGI® Sabor Carne y la carne de res. Cocinar por 5 minutos.

3.  Agregar el olluco picado y 2 tazas de agua. Cocinar a fuego medio por 10 minutos.

4.  Agregar la papa cortada en trozos y cocinar por 5 minutos más.

5.  Servir el olluco acompañado de una taza de arroz. Decorar con las hojas de perejil cortado.''','img_url': 'https://larepublica.pe/resizer/jWbE2EywtQhDBtfzWvBeq2U9hTE=/1250x735/top/smart/arc-anglerfish-arc2-prod-gruporepublica.s3.amazonaws.com/public/BZ7INOAM2VAGHLSKPGR52E2DVQ.png'},
{'Nombre': 'Ají de gallina', 'Ingredientes': ['gallina', 'papa', 'ají panca', 'ají amarillo', 'cebollas', 'ajos', 'pan', 'leche', 'queso parmesano', 'maní', 'pecanas', 'sal', 'pimientas', 'aceitunas', 'huevo'], 'Instrucciones': '''En una olla con agua, cocer la pechuga de gallina con un poquito de aceite de oliva, la hoja de laurel y sal.  
Retirar del fuego, reservando el caldo de la cocción en una jarra. Deshilachar la pechuga en trozos grandes o finos según se prefiera y reservar en un bol.
En la cuba de una procesadora, añadir el pan desmigado y la leche. Dejar en remojo antes de triturar.  
En una olla, calentar aceite de oliva. Mientras tanto picar la cebolla en brunoise e incorporar a la olla junto con la pasta de ajo y la de ají amarillo.
Licuar el pan con leche, hasta que no queden grumos. Verter en la olla, disminuir el fuego a medio y remover constantemente para que no se pegue al fondo.
Agregar luego la gallina deshilachada. Una vez que empiece a espesar, añadir un buen chorro del caldo reservado. Condimentar con un poquito de comino. Remover.
Picar las nueces. Seguir cociendo y según vaya espesando ir añadiendo el agua de la cocción de la gallina. Corregir de sal.
Agregar el queso parmesano rallado y seguir revolviendo por 2 o 3 minutos más -la consistencia final no debe ser demasiado densa ni demasiado líquida-.  
Servir el ají de gallina sobre las rodajas de papas cocidas. Acompañar con mitades de huevo duro y aceitunas de botija.''','img_url': 'https://www.gourmet.cl/wp-content/uploads/2016/09/Aji-Gallina-web-570x458.jpg'},
{'Nombre': 'Salpicón de pollo', 'Ingredientes': ['pechuga de pollo', 'arvejas', 'papa', 'lechuga', 'mayonesa', 'zanahoria', 'sal', 'pimienta'], 'Instrucciones': '''Cocina la pechuga de pollo en agua. Una vez cocida deshebra con cuidado y coloca en un recipiente grande.
Agrega en un recipiente el tomate, cebolla, zanahoria, lechuga, aceite de oliva, jugo de limón o vinagre, orégano, sal y pimienta. De ser necesario agregar más jugo de limón al gusto.
Mezcla bien y sirve con tostadas y aguacate.
''','img_url': 'https://lascomidasperuanas.com/wp-content/uploads/2021/07/Receta-de-salpicon-de-pollo-peruano.jpg'},
{'Nombre': 'Papa a la huancaína', 'Ingredientes': ['papa', 'ají amarillo', 'cebolla', 'aceite', 'leche', 'queso crema', 'galleta soda', 'sal', 'pimienta'], 'Instrucciones': '''Pelar el ají, quitarle el centro y sus nervaduras, cortarlo en trozos.
Ponerlo en la licuadora con la leche evaporada, las galletas, el queso de cabra y sal.
Verter aceite en cantidad suficiente y en forma de hilo como para obtener una salsa densa y amarilla.
Pasar la salsa por tamiz, distribuir en los platos las papas cortadas en ruedas, cubrirlas con la salsa fría y decorar con medios huevos duros, hojas de lechuga y aceitunas negras.''','img_url': 'https://www.lanacion.com.ar/resizer/ihFgftiHscquFdAie8AbkMJCuX4=/1200x800/filters:format(webp):quality(80)/cloudfront-us-east-1.images.arcpublishing.com/lanacionar/XSHZH7X5ZJFNHCFJI3YQCGNMOY.jpg'},
{'Nombre': 'Escabeche de pollo', 'Ingredientes': ['pollo', 'cebolla', 'aceituna negra', 'ají verde', 'vinagre', 'ajo', 'azucar', 'aceite', 'huevo duro', 'sal', 'pimienta'], 'Instrucciones': '''1. primeros pasos para preparar nuestro escabeche de pollo será sancochar, o cocinar en agua hirviendo, las presas de pollo junto con un poco de sal y pimienta.

Aprovecha y ve cortando las cebollas y los ajíes en tiras gruesas.

2.
Aparte, calentamos aceite en una cacerola y cocinamos las cebollas junto con el ají fresco, el ají molido, orégano, sal y pimienta. Mantenemos la cocción unos minutos para luego añadir el vino y el vinagre y remover todo.

También puedes añadir zanahorias a la preparación, lo importante es que todo esté cortado igual, en tiras gruesas.

3.
A continuación incorporamos las presas de pollo cocidas y dejamos cocinar a fuego bajo hasta reducir la salsa al gusto. Este procedimiento puede tardar unos 30-45 minutos.

4.
Cuando el pollo en escabeche tradicional esté listo, servimos en una fuente y decoramos con con hojas de lechuga, huevos cocidos y aceitunas.''','img_url': 'https://t1.rg.ltmcdn.com/es/posts/9/8/8/escabeche_de_pollo_peruano_41889_600.webp'},
{'Nombre': 'Sopa de olluco', 'Ingredientes': ['ollucos', 'leche', 'aceite', 'queso', 'papas', 'cebolla', 'perejil', 'culantro', 'ají', 'oregano', 'ajo', 'huevo', 'hierbabuena', 'caldo de carne', 'sal', 'pimienta'], 'Instrucciones':'''Caliente el aceite en una olla a fuego medio y fría la cebolla, el ajo y el ají por cinco minutos. Sazone con el orégano, la hierbabuena, sal y pimienta.
Añada el caldo y cocine removiendo hasta hervir. Agregue los ollucos y cocine por 10 minutos. Incorpore las papas y cocine por 10 minutos más.
Añada el queso, las habas y los huevos batidos y hierva removiendo por unos minutos. Vierta la leche.
Añada el culantro y el perejil y sirva.''','img_url': 'https://jameaperu.com/wp-content/uploads/2019/07/sopa-de-ollucos_700x465.jpg'},
{'Nombre': 'Arroz con langostinos', 'Ingredientes': ['arroz', 'langostinos', 'aceite vegetal', 'cebolla roja', 'ajos', 'tomates', 'pasta de tomate', 'zanahoria', 'alverjas', 'orégano', 'vino blanco', 'pimientos morrones', 'culantro', 'sal', 'pimienta'], 'Instrucciones': '''Pelamos los langostinos y separamos las colas. En una sartén con un fondo de aceite salteamos las cáscaras y las cabezas hasta que vemos que han cambiado de color. Añadimos el vino y dejamos que evapore el alcohol.
Agregamos un litro de agua y el laurel y dejamos que hierva todo unos 15 minutos y probamos de sal para que resulte sabroso. Le vamos dando con la espumadera para que las cabezas suelten todo el sabor. Colamos el caldo y reservamos.
Abrimos las almejas o mejillones al vapor y colamos también el caldo para unirlo al anterior.
En una cazuela con aceite rehogamos el tomate picado o triturado y en cuanto empiece a tomar color ponemos pimentón, removemos para que se integre y añadimos el arroz. Damos unas vueltas.
Agregamos el caldo y dejamos a fuego lento entre 17 y 20 minutos según el tipo de arroz. Regulamos el nivel de caldo si es necesario añadiendo un poco de agua y controlando el punto de sal.
Mientras tanto en una sartén con aceite de oliva doramos los ajos laminados. Cuando empiecen a tomar color añadimos los langostinos, salpimentamos y revolvemos para que vayan tomando color. No deben hacerse mucho para que no se resequen, un par de minutos nos deben bastar.
Cuando apartemos el arroz para dejarlo reposar añadimos los langostinos con los ajos, mezclamos bien y dejamos reposar 10 minutos antes de servir espolvoreado con perejil fresco picado.''','img_url': 'https://www.hogarmania.com/archivos/201906/arroz-con-langostinos-xl-668x400x80xX.jpg'},
{'Nombre': 'Arroz a la tumbada', 'Ingredientes': ['1 ½ tazas de arroz','1 jaiba troceada','10 almejas','10 mejillones','8 camarones medianos','2 tazas de caldo de pescado','5 jitomates maduros','½ cebolla picada','2 dientes de ajo picados','3 cdas. de aceite','4 cdas. de perejil picado'], 'Instrucciones':'Licua los jitomates con el caldo de pescado, salpimienta y reserva.En una arrocera sofríe el arroz, la cebolla y el ajo con el aceite; cuando comiencen a dorar agrega el caldillo.Cuando empiece a hervir agrega los mariscos, tapa con papel aluminio y cuece a fuego bajo durante 15 minutos.Termina con el perejil y sirve.','img_url': 'https://dam.cocinafacil.com.mx/wp-content/uploads/2020/03/arroz-a-la-tumbada.jpg'},
{'Nombre': 'Espagueti con verduras y tofu', 'Ingredientes': ['400 g de espagueti','1/2 manojo de espárragos','2 dientes de ajo picados',	'2 tazas de espinaca baby','1/2 tazas de setas rebanadas','2 cucharadas de ajonjolí negro','300 g de tofu en rectángulos medianos','2 cucharadas de aceite de oliva','2 cucharadas de mantequilla','4 cucharadas de salsa de soya'], 'Instrucciones':'Cuece la pasta hasta que esté suave.	Mientras tanto saltea los espárragos con el ajo, las setas y el aceite de oliva; cuando comiencen a dorar agrega la mantequilla y la espinaca; salpimienta.	Salpimienta el tofu y ásalo en una sartén con un poco de aceite de oliva hasta que esté dorado, agrégalo a las verduras.	Integra la pasta, añade la salsa de soya y el aceite de ajonjolí. Sirve y termina con un poco de semillas de ajonjolí negro.	Cuece la pasta hasta que esté suave.	Mientras tanto saltea los espárragos con el ajo, las setas y el aceite de oliva; cuando comiencen a dorar agrega la mantequilla y la espinaca; salpimienta.	Salpimienta el tofu y ásalo en una sartén con un poco de aceite de oliva hasta que esté dorado, agrégalo a las verduras.	Integra la pasta, añade la salsa de soya y el aceite de ajonjolí. Sirve y termina con un poco de semillas de ajonjolí negro.','img_url': 'https://dam.cocinafacil.com.mx/wp-content/uploads/2013/07/espagueti-con-verduras-y-tofu.jpg'},
{'Nombre': 'Champiñones con espinaca y ajo', 'Ingredientes': ['8 champiñones grandes','1/2 taza de queso de cabra','1/2 taza de espinaca cocida y picada',	'2 huevos',	'2 dientes de ajo','1 cucharada de mantequilla','1 pizca de nuez moscada'], 'Instrucciones':'Sofríe el ajo con la mantequilla; cuando comience a dorar agrégalo a un tazón y mézclalo con la espinaca, el queso de cabra, el huevo y la nuez moscada. Salpimienta.	Coloca una cucharada sobre los champiñones y hornea durante 10 minutos a 180º C.	Sirve calientes.','img_url': 'https://dam.cocinafacil.com.mx/wp-content/uploads/2018/11/champinones-con-espinaca-y-ajo.jpg'},
{'Nombre': 'Cebiche de camarón en jitomate', 'Ingredientes': ['4 jitomates bola', '3 cebollas moradas picada finamente', '1/2 c de pepino picado', '4 tbsp. de cilantro picado', '5 tbsp. de jugo de limón', 'camarón cocido', '1 chile serrano picado', '2 tbsp. de aceite de oliva '], 'Instrucciones':'Mezcla todos los ingredientes excepto el jitomate, y salpimienta.Ahueca los jitomates con cuidado y rellénalos con el cebiche. Llévalos a la mesa. ','img_url': 'https://dam.cocinafacil.com.mx/wp-content/uploads/2018/01/Cebiche-de-camaron.jpg'},
{'Nombre': 'Ensalada de garbanzos y quinoa', 'Ingredientes': ['250g de quinoa', '150g de garbanzos', '100g de guisantes', '1 cebolla', '1 tomate', 'El jugo de 1 limón', '2 ramas de hierbabuena fresca', '1 puñadito de perejil fresco','sal y pimienta','aceite de oliva'], 'Instrucciones':'En una olla a presión, ponemos a calentar a fuego medio una buena cantidad de agua y le añadimos un puñadito de sal. Lavamos y añadimos también los garbanzos, que habrán pasado la noche a remojo junto con un poco de bicarbonato. Dejamos que se cocinen durante 30 minutos, los escurrimos y los dejamos enfriar.	Mientras tanto, en una cazuela con abundante agua, añadimos un par de pizcas de sal y lo calentamos a fuego fuerte hasta que hierva. Añadimos la quinoa lavada y los guisantes, y dejamos que se cocinen aquí durante 15 minutos, removiendo de vez en cuando. Pasado este tiempo, escurrimos todo y lo reservamos.	Montamos la ensalada de garbanzos y quinoa. Después, en una ensaladera amplia, ponemos el tomate y la cebolla cortados en trozos pequeños. Añadimos los garbanzos, la quinoa y los guisantes y lo mezclamos todo.	A continuación, ponemos en un recipiente el jugo del limón, un chorrete de aceite, la hierbabuena y el perejil bien picados. Lo mezclamos bien con un tenedor y se lo echamos por encima a la ensalada. Removemos para que se reparta bien el aliño, y… ¡a servir!','img_url': 'https://www.conasi.eu/blog/wp-content/uploads/2018/08/destacada2_ensalada-quinoa-y-garbanzos.jpg'},
{'Nombre': 'Salmon ahumado con aguacate y palitos de cangrejo', 'Ingredientes': ['250g de salmón ahumado en lonchas', '2 aguacates', 'crema de queso', 'palitos de cangrejo o surimi', '500g de espinacas frescas', 'eneldo', 'limón'], 'Instrucciones':'''En primer lugar debemos elegir un salmón ahumado -no marinado-, que se encuentre en lonchas enteras, ya que si lo compramos en trozos nos resultará difícil trabajar con él. Una vez en casa, vamos a abrir la bandeja y dejar que se oxigene durante unos minutos. Mientras tanto podemos ir preparando el resto de los ingredientes.
A continuación vamos a cocer las espinacas. Llenamos dos ollas grandes de agua. A una de ellas le añadimos un puñadito de sal y la llevamos a ebullición. Cuando rompa a hervir añadimos las espinacas. Dejamos que cuezan aproximadamente un minuto y retiramos las mismas a la olla de agua fria. Así cortaremos la cocción de las espinacas y evitaremos que pierdan propiedades  y mantengan el color verde.
Ahora vamos con el aguacate, al que vamos a retirar la pulpa ayudándonos de una cuchara, repasándolo por los bordes y eliminando el hueso central. Cortamos el aguacate en tiras, en forma de bastoncillos y añadimos unas gotitas de limón para dar sabor y evitar que se oxiden. Los reservamos en un plato.
Untamos una loncha de salmón con el la crema de queso. En el lateral por el que empezaremos a enrollar colocamos los bastoncitos de aguacate, junto con un poco de los palitos de cangrejo también en forma de tiras o bastoncillos, un puñado de las espinacas bien escurridas y un poquito de eneldo picado.
Enrollamos con cuidado, procurando que los ingredientes queden juntos en el centro.
Cuando hayamos acabado de hacer todos los rollitos, espolvoreamos con un poco más eneldo.''','img_url': 'https://assets.tmecosys.com/image/upload/t_web667x528/img/recipe/ras/Assets/CF884770-46A6-49F1-BF24-E7C4E6EE5FE2/Derivates/2B21A4A1-90F3-4AB7-97CC-DE14743FBE44.jpg'},
{'Nombre': 'Alcachofas con almejas', 'Ingredientes': ['500g de alcachofas', '1 cebolla', '4 dientes de ajo', 'perejil fresco', '1 cucharada de harina', '200 ml de vino blanco', '1 cucharada de jugo de limón', '200 g de almejas frescas','sal y pimienta','aceite de oliva'], 'Instrucciones':'''Lavamos y limpiamos las alcachofas. Eliminamos la parte superior fibrosa, el rabillo y todas las hojas demasiado verdes. Nos quedaremos por tanto con el corazón y las hojas más carnosas de la alcachofa. Hecho esto las dividimos en dos mitades y las cocemos en abundante agua hirviendo durante 15 minutos, junto con un puñadito de sal. Cuando estén cocidas, reservamos por un lado las alcachofas y por otro, su caldo.
En una sartén amplia, añadimos un chorro generoso de aceite y lo calentamos a fuego medio. Cuando esté caliente añadimos la cebolla bien picada, salpimentamos y dejamos que se cocine 10 minutos, removiendo de vez en cuando, hasta que se ablande.
Pasado el tiempo añadimos el ajo y el perejil, todo ello bien picado, y lo cocinamos 5 minutos, removiendo con frecuencia.
Hecho esto, añadimos la harina y la mezclamos bien con el resto de los ingredientes. Dejamos que se cocine 3 minutos removiendo constantemente.
Ahora vamos a añadir el vino. Dejamos que se evapore el alcohol durante 2 minutos y lo mezclamos bien. Si crees que la salsa es demasiado densa, puedes añadir un poco del caldo de las alcachofas, hasta conseguir la consistencia deseada, ni demasiado caldosa, ni demasiado densa.
Hecho esto, cortamos en dos partes cada mitad de alcachofa y las añadimos a la sartén junto con el jugo de limón. Salpimentamos y mezclamos bien. Dejamos que se cocinen 5 minutos para que absorban los jugos del resto de ingredientes.
Una vez se cocinen, añadimos las almejas y dejamos que se cocinen 2 minutos. Cuando se abran, mezclamos bien con la salsa, corregimos de sal y pimienta, y la receta estará acabada.''','img_url': 'https://recetasdecocina.elmundo.es/wp-content/uploads/2019/02/receta-alcachofas-almejas.jpg'},
{'Nombre': 'Paella festiva', 'Ingredientes': ['1/8 cucharadita de hilos de azafrán machacados', '2 tazas de caldo de pollo', '1 pimiento (pimentón) rojo, cortado por la mitad a lo largo', '1/4 taza de aderezo italiano fuerte KRAFT Zesty Italian Dressing', '1 lata (14-1/2 oz.) de tomates (jitomates) en cubitos, escurridos', '1/2 taza de cebolla picada', '1/2 taza de cebolla picada', '2 dientes de ajo, bien picados','1 libra de pechuga de pollo deshuesada y sin pellejo, cortada en trozos tamaño bocado', '1/2 libra de salchicha italiana, cortada en trozos de 1 pulgada', '1 paquete (6 oz.) de jamón con miel OSCAR MAYER Honey Ham, picado', '3 rebanadas de tocino (tocineta) OSCAR MAYER Bacon, bien picado', '1 taza de arroz blanco de grano largo de grano largo, sin cocinar', '1 libra de camarones limpios, sin cocer, pelados y desvenados', '12 mejillones, limpios, cepillados y sin barbas', '1 taza de ejotes (habichuelas verdes), descongelados'], 'Instrucciones':'Calienta el horno a 325°F. Mezcla el azafrán con el caldo de pollo; pon a un lado. Corta la mitad del pimiento rojo en tiras; separa. Pica el resto del pimiento. Calienta el aderezo en una sartén grande apta para horno a fuego medio. Incorpora el pimiento picado, los tomates, la cebolla y el ajo; cocina 5 min. o hasta que los pimientos y las cebollas estén tiernos y crujientes, revolviendo frecuentemente. Agrega el pollo, la salchicha, el jamón y el tocino; revuelve. Cocina 10 min., revolviendo frecuentemente. Reduce el fuego a mínimo. Agrega la mezcla de caldo de pollo; mezcla bien. Haz hervir; agrega el arroz y revuelve. Coloca los camarones, los mejillones, los ejotes y las tiras de pimiento rojo sobre el arroz; tápala. Sácala del fuego. Hornea durante 20 min. o hasta que los mejillones se abran y los camarones se vuelvan rosados. Deja reposar 5 min. antes de servir. (Descarta los mejillones que no se hayan abierto).','img_url': 'https://assets.kraftfoods.com/recipe_images/opendeploy/Festive-Skillet-Paella-22293_640x428.jpg'},
{'Nombre': 'Bacalao a la sartén con ensalada de frijoles blancos', 'Ingredientes': ['1/2 taza de aderezo italiano fuerte KRAFT Zesty Italian Dressing, cantidad dividida','1 cucharadita de páprika ahumada','6 filetes de bacalao fresco (1-1/2 lb)', '2 latas (15.5 oz cada una) de frijoles norteños, enjuagados', '1 tomate (jitomate) grande, sin semillas y picado', '4 cebollitas verdes, en rebanadas finas', '1/4 taza de perejil fresco picado', '1 diente grande de ajo, bien picado', '1/2 taza de aceitunas negras sin hueso, en rebanadas', '3 huevos duros, cortados en cuñas'], 'Instrucciones':'Mezcla 1/4 taza de aderezo con la páprika; vierte la mezcla sobre el pescado en un plato llano. Voltea el pescado para cubrir parejamente por ambos lados cada filete. Ponlos a marinar en la nevera durante 30 min. Mezcla los ingredientes restantes, entretanto, excepto las aceitunas y los huevos, en un tazón grande. Saca el pescado de la marinada y deshazte de ésta. Cocina el pescado en una sartén grande a fuego medio-alto de 4 a 5 min. por lado o hasta que el pescado se desmenuce fácilmente con un tenedor. Sírvelo con la ensalada de frijoles; corona todo con las aceitunas y los huevos.','img_url': 'https://assets.kraftfoods.com/recipe_images/opendeploy/115352_640x428.jpg'},
{'Nombre': 'Gambas a la plancha', 'Ingredientes': ['Gamba blanca o roja, grande, de calidad', 'Papel de hornear recortado a medida de la plancha', 'Aceite de oliva virgen extra un chorrito', 'Sal gruesa abundante'], 'Instrucciones':'Comenzamos recortando un papel de hornear, de la medida de la plancha en que vayamos a cocinar las gambas. Después haremos las gambas a la plancha sobre este papel, que deja pasar perfectamente el calor pero protege a la plancha de olores, líquidos y evita que se peguen los alimentos. Sobre el papel, colocamos las gambas, todas alineadas y mirando en la misma dirección. Así, cuando les demos la vuelta a mitad de la cocción tendremos claro a las que ya hemos dado la vuelta, evitando que alguna se haga solo por un lado. En la zona donde la cabeza y el cuerpo de la gamba se juntan, ponemos unos granillos de sal gruesa, como podéis ver en el collage de más abajo. Después, añadimos un chorrito o hilo de aceite de oliva virgen extra y dejamos que se cocinen, a fuego máximo, durante dos minutos. Pasado ese tiempo, damos la vuelta a las gambas con unas pinzas, y dejamos que se cocinen por el otro lado otro minuto o dos minutos más, dependiendo del calibre y grosor de las gambas, sacándolas a una fuente y degustándolas inmediatamente. Sobre la plancha, quedará el papel de hornear manchado, que podemos arrugar y tirar, quedando la plancha limpia y lista para el siguiente uso.','img_url': 'https://i.blogs.es/ce9b9a/gambas-a-la-plancha-perfectas-pakus-directo-al-paladar-futurobloguero/1366_2000.jpg'},
{'Nombre': 'Cookies de avena, plátano y almendras', 'Ingredientes': ['100 gramos de avena', '2 plátanos medianos', '30 gramos de almendras', 'canela'], 'Instrucciones':'Para comenzar a elaborar estas cookies simplemente debemos colocar en un recipiente la avena y los plátanos en trozos grandes. Con un tenedor comenzamos a pisar los plátanos mientras los unimos con la avena. Cuando estos ingredientes están unidos agregamos las almendras picadas groseramente y si deseamos, una cucharadita de canela. En esta ocasión no hemos añadido azúcar, pero si se desea se puede agregar una cucharada de miel, aunque no lo considero necesario. En una placa para horno antiadherente colocamos con ayuda de una cuchara las cookies y les damos forma redonda hasta dejarlas finas. Precalentamos el horno fuerte y horneamos por 15 a 20 minutos.','img_url': 'https://img-global.cpcdn.com/recipes/d279deecabfdd6f1/640x640sq70/photo.webp'},
{'Nombre': 'Barritas fitness de avena y frutos secos', 'Ingredientes': ['Higos secos o deshidratados', 'Zumo de naranja recién exprimido', 'Estevia líquida', 'Copos de avena', 'Coco rallado', 'Almendras', 'Nueces', 'Agua cantidad necesaria'], 'Instrucciones':'Para elaborar estas barritas fitness comenzaremos colocando en una batidora o en el vaso de un motor de cocina los higos secos junto a la stevia líquida y el zumo de dos gajos de naranja (aproximadamente 4 cucharadas). Accionamos el motor y procesamos hasta obtener una pasta consistente pero húmeda, si fuera necesario agregamos agua poco a poco de a cucharadas hasta obtener una pasta de higos. En un bol mezclamos los higos con todos los ingredientes secos: los copos de avena (yo los procesé un poco para que queden más pequeños), el coco rallado, las nueces picadas groseramente y las almendras partidas por la mitad. En este punto se puede agregar más agua si fuese necesario o más edulcorante si habiendo probado nos parece que falta dulzor. Unimos todos los ingredientes con ayuda de una cuchara o usando las manos para lograrlo y en un recipiente rectangular colocamos la preparación, aplanando la misma y extendiendo hasta que alcance un centímetro de grosor. Marcamos las barritas (rectangulares o cuadradas) y las llevamos al refrigerador por una hora. Pasado dicho tiempo las barritas estarán firmes, consistentes y crocantes. Desmoldamos y listas para consumir.','img_url': 'https://i.blogs.es/4cc5cf/barritasfitness/1366_2000.webp'},
{'Nombre': 'Brochetas de cerdo marinadas con salsa de maní', 'Ingredientes': ['25 palos de bambú','600 gr de solomillo de cerdo','1 diente de ajo picado fino',	'1 vara de lemongrass picada fina',	'1 cucharadita de ralladura de limón',	'1/2 cucharadita de semillas de cilantro machacadas',	'3 cucharadas de salsa de ostras',	'2 cucharadas de vinagre',	'3 cucharadas de aceite de oliva',	'1/2 taza (120 ml) de salsa de soya','1 cucharada de mantequilla',	'1/2 cucharada de pimienta negra entera	Para la Salsa de Maní','2 cucharadas de mantequilla de maní',	'1 cucharada de vinagre blanco',	'1/4 cucharada de paprika o pimentón molido',	'2 cucharadas de crema	Sal y pimienta'	], 'Instrucciones':'1.Prepare las brochetas. En los palos de bambú inserte las láminas de cerdo hasta completar los 25 palos. Coloque en una fuente y reserve.		2. Prepare la marinada. En un bol coloque todos los ingredientes de la marinada, excepto la mantequilla y la pimienta. Mezcle bien y luego vierta sobre la fuente con las brochetas. Tape con un papel plástico y refrigere por 3 horas.		3. Retire las brochetas de la fuente y estile. Reserve la marinada. En una sartén coloque la mantequilla y los granos de pimienta; caliente a fuego medio y agregue las brochetas. Cocine hasta que las brochetas estén cocidas y doradas. Retire del fuego y conserve el calor.		4. Prepare la salsa de maní. En la misma sartén coloque 2/3 de agua fría, mantequilla de maní, vinagre, paprika, crema y la marinada reservada. Cocine revolviendo, hasta calentar y sazone con sal y pimienta. Retire del fuego y sirva de inmediato junto con las brochetas de cerdo.','img_url': 'https://2.bp.blogspot.com/-gcw7DOPNyL4/U2l6im_H4KI/AAAAAAAAAIo/iOPLADCNYQU/s1600/Brochetas+de+Cerdo+con+Salsa+de+Man%C3%AD.jpg'},
{'Nombre': 'Crema de mariscos', 'Ingredientes': ['1 puerro''1 pimiento rojo','1 cebolla''300 g de langostinos','1 kg de mejillones cocidos','2 patas grandes de pulpo','1 cda. de pimentón','1 ½ de caldo de pescado','100 mL de crema'], 'Instrucciones':'Corta en trozos el poro, la cebolla y el pimiento rojo. Agrega los langostinos enteros, los mejillones ya cocidos y el pulpo. Remueve y agrega una cucharada de pimentón. Agrega el caldo de pescado y cocina a fuego lento durante unos 25 a 30 minutos. Retira la cáscara de los langostinos y pasa por la batidora o licuadora. Cuela la mezcla para que quede una crema muy fina. Incorpora la crema y sazona con sal al gusto.','img_url': 'https://www.comedera.com/wp-content/uploads/2019/02/crema-de-marisco.jpg'},
]



#https://drive.google.com/file/d/1xKDzb3cBpYFZIoLxPCsoc5C4OzDqPetr/view?usp=sharing
#https://drive.google.com/uc?id=1xKDzb3cBpYFZIoLxPCsoc5C4OzDqPetr


alergiasData = {'Mariscos': ['camaron, cangrejo','almeja','pulpo','langostinos'],'Lácteos':['leche','queso'],
'Gluten':['trigo', 'avena', 'cebada', 'centeno']} #alimentos en 

ingredientes_recetas = set()
for receta in recetas:
  if receta["img_url"] != "file/d/":
    receta["img_url"] = receta["img_url"].replace("file/d/","uc?id=")
    receta["img_url"] = receta["img_url"].replace("/view?usp=sharing","")

  for ingrediente in receta['Ingredientes']:
    ingredientes_recetas.add(ingrediente)
