recetas = [
    
<<<<<<< HEAD
{'Nombre': 'licuado_desayuno', 'Ingredientes': ['fresas', 'yogurt natural', 'estevia', 'naranja'], 'Instrucciones': 'Tomas diez fresas les añades una taza de yogurt natural, adicionas un sobre de estevia (edulcorante) y el jugo de media naranja, mezclas todo y lo licuas de 2 a 3 minutos.', 'img_url': ''} ,
{'Nombre': 'jambalaya_pollo', 'Ingredientes': ['jamon', 'caldo', 'pollo', 'pimienta', 'aceite oliva', 'apio', 'cebolla', 'pimenton pimiento', 'ajo', 'arroz'], 'Instrucciones': 'En una cazuela colocas 450g de jamón y 1 1/2 vasos de agua, los cocinas por minutos, mientras cortas 450g de pollo y 1 rama de apio en cubos, pasado el tiempo escurres el jamón, luego colocas 2 cucharadas de aceite de oliva y sofries el apio previamente cortado, 2 dientes de ajo y 1/4 de cebolla. Una vez sofreido, salpimentas el pollo y lo añades a la mezcla para freirlo, ya todo freido, agregas el jamón y 1 taza de arroz, después agregas 2 1/2 tazas de caldo y dejas que cueza el arroz, una vez cocido puedes servir.', 'img_url': ''} ,
{'Nombre': 'latte_calabaza', 'Ingredientes': ['puren calabaza', 'estevia', 'canela', 'jengibre', 'nuez moscada', 'leche', 'cafe', 'nata'], 'Instrucciones': 'Falta instrucciones', 'img_url': ''} ,
{'Nombre': 'Carapulca chinchana', 'Ingredientes': ['fideos', 'pollo', 'ajo molido', 'cebolla', 'comino', 'achiote molido', 'tomate', 'albahaca', 'perejil', 'aceite', 'cerdo', 'papa', 'ají', 'pimienta', 'yuca'], 'Instrucciones': 'Falta instrucciones', 'img_url': ''} ,
{'Nombre': 'Olluquitos con carne', 'Ingredientes': ['ollucos', 'carne', 'ají mirasol', 'cebolla', 'aceite', 'ajo', 'oregano', 'sal', ' pimienta'], 'Instrucciones': 'Falta instrucciones', 'img_url': ''} ,
{'Nombre': 'Ají de gallina', 'Ingredientes': ['gallina', 'papa', 'ají panca', 'ají amarillo', 'cebollas', 'ajos', 'pan', 'leche', 'queso parmesano', 'maní', 'pecanas', 'sal', 'pimientas', 'aceitunas', 'huevo'], 'Instrucciones': 'Falta instrucciones', 'img_url': ''} ,
{'Nombre': 'Salpicón de pollo', 'Ingredientes': ['pechuga de pollo', 'arvejas', 'papa', 'lechuga', 'mayonesa', 'zanahoria', 'sal', 'pimienta'], 'Instrucciones': 'Falta instrucciones', 'img_url': ''} ,
{'Nombre': 'Papa a la huancaína', 'Ingredientes': ['papa', 'ají amarillo', 'cebolla', 'aceite', 'leche', 'queso crema', 'galleta soda', 'sal', 'pimienta'], 'Instrucciones': 'Falta instrucciones', 'img_url': ''} ,
{'Nombre': 'Escabeche de pollo', 'Ingredientes': ['pollo', 'cebolla', 'aceituna negra', 'ají verde', 'vinagre', 'ajo', 'azucar', 'aceite', 'huevo duro', 'sal', 'pimienta'], 'Instrucciones': 'Falta instrucciones', 'img_url': ''} ,
{'Nombre': 'Sopa de olluco', 'Ingredientes': ['ollucos', 'leche', 'aceite', 'queso', 'papas', 'cebolla', 'perejil', 'culantro', 'ají', 'oregano', 'ajo', 'huevo', 'hierbabuena', 'caldo de carne', 'sal', 'pimienta'], 'Instrucciones': 'Falta instrucciones', 'img_url': ''} ,
{'Nombre': 'Arroz con langostinos', 
'Ingredientes': ['arroz', 'langostinos', 'aceite vegetal', 'cebolla roja', 'ajos', 'tomates', 'pasta de tomate', 'zanahoria', 'alverjas', 'orégano', 'vino blanco', 'pimientos morrones', 'culantro', 'sal', 'pimienta'], 
'Instrucciones': 'Falta instrucciones', 
'img_url': 'https://drive.google.com/file/d/1xKDzb3cBpYFZIoLxPCsoc5C4OzDqPetr/view?usp=sharing'} 
=======
{'Nombre': 'licuado_desayuno', 'Ingredientes': ['fresas', 'yogurt natural', 'estevia', 'naranja'], 'Instrucciones': 'Tomas diez fresas les añades una taza de yogurt natural, adicionas un sobre de estevia (edulcorante) y el jugo de media naranja, mezclas todo y lo licuas de 2 a 3 minutos.'},
{'Nombre': 'jambalaya_pollo', 'Ingredientes': ['jamon', 'caldo', 'pollo', 'pimienta', 'aceite oliva', 'apio', 'cebolla', 'pimenton pimiento', 'ajo', 'arroz'], 'Instrucciones': 'En una cazuela colocas 450g de jamón y 1 1/2 vasos de agua, los cocinas por minutos, mientras cortas 450g de pollo y 1 rama de apio en cubos, pasado el tiempo escurres el jamón, luego colocas 2 cucharadas de aceite de oliva y sofries el apio previamente cortado, 2 dientes de ajo y 1/4 de cebolla. Una vez sofreido, salpimentas el pollo y lo añades a la mezcla para freirlo, ya todo freido, agregas el jamón y 1 taza de arroz, después agregas 2 1/2 tazas de caldo y dejas que cueza el arroz, una vez cocido puedes servir.'},
{'Nombre': 'latte_calabaza', 'Ingredientes': ['puren calabaza', 'estevia', 'canela', 'jengibre', 'nuez moscada', 'leche', 'cafe', 'nata'], 'Instrucciones': 'Falta instrucciones'},
{'Nombre': 'Carapulca chinchana', 'Ingredientes': ['fideos', 'pollo', 'ajo molido', 'cebolla', 'comino', 'achiote molido', 'tomate', 'albahaca', 'perejil', 'aceite', 'cerdo', 'papa', 'ají', 'pimienta', 'yuca'], 'Instrucciones': 'Falta instrucciones'},
{'Nombre': 'Olluquitos con carne', 'Ingredientes': ['ollucos', 'carne', 'ají mirasol', 'cebolla', 'aceite', 'ajo', 'oregano', 'sal', ' pimienta'], 'Instrucciones': 'Falta instrucciones'},
{'Nombre': 'Ají de gallina', 'Ingredientes': ['gallina', 'papa', 'ají panca', 'ají amarillo', 'cebollas', 'ajos', 'pan', 'leche', 'queso parmesano', 'maní', 'pecanas', 'sal', 'pimientas', 'aceitunas', 'huevo'], 'Instrucciones': 'Falta instrucciones'},
{'Nombre': 'Salpicón de pollo', 'Ingredientes': ['pechuga de pollo', 'arvejas', 'papa', 'lechuga', 'mayonesa', 'zanahoria', 'sal', 'pimienta'], 'Instrucciones': 'Falta instrucciones'},
{'Nombre': 'Papa a la huancaína', 'Ingredientes': ['papa', 'ají amarillo', 'cebolla', 'aceite', 'leche', 'queso crema', 'galleta soda', 'sal', 'pimienta'], 'Instrucciones': 'Falta instrucciones'},
{'Nombre': 'Escabeche de pollo', 'Ingredientes': ['pollo', 'cebolla', 'aceituna negra', 'ají verde', 'vinagre', 'ajo', 'azucar', 'aceite', 'huevo duro', 'sal', 'pimienta'], 'Instrucciones': 'Falta instrucciones'},
{'Nombre': 'Sopa de olluco', 'Ingredientes': ['ollucos', 'leche', 'aceite', 'queso', 'papas', 'cebolla', 'perejil', 'culantro', 'ají', 'oregano', 'ajo', 'huevo', 'hierbabuena', 'caldo de carne', 'sal', 'pimienta'], 'Instrucciones': 'Falta instrucciones'},
{'Nombre': 'Arroz con langostinos', 'Ingredientes': ['arroz', 'langostinos', 'aceite vegetal', 'cebolla roja', 'ajos', 'tomates', 'pasta de tomate', 'zanahoria', 'alverjas', 'orégano', 'vino blanco', 'pimientos morrones', 'culantro', 'sal', 'pimienta'], 'Instrucciones': 'Falta instrucciones'},
{'Nombre': 'Arroz a la tumbada', 'Ingredientes': ['1 ½ tazas de arroz','1 jaiba troceada','10 almejas','10 mejillones','8 camarones medianos','2 tazas de caldo de pescado','5 jitomates maduros','½ cebolla picada','2 dientes de ajo picados','3 cdas. de aceite','4 cdas. de perejil picado'], 'Instrucciones':'Licua los jitomates con el caldo de pescado, salpimienta y reserva.En una arrocera sofríe el arroz, la cebolla y el ajo con el aceite; cuando comiencen a dorar agrega el caldillo.Cuando empiece a hervir agrega los mariscos, tapa con papel aluminio y cuece a fuego bajo durante 15 minutos.Termina con el perejil y sirve.'},
{'Nombre': 'Espagueti con verduras y tofu', 'Ingredientes': ['400 g de espagueti','1/2 manojo de espárragos','2 dientes de ajo picados',	'2 tazas de espinaca baby','1/2 tazas de setas rebanadas','2 cucharadas de ajonjolí negro','300 g de tofu en rectángulos medianos','2 cucharadas de aceite de oliva','2 cucharadas de mantequilla','4 cucharadas de salsa de soya'], 'Instrucciones':'Cuece la pasta hasta que esté suave.	Mientras tanto saltea los espárragos con el ajo, las setas y el aceite de oliva; cuando comiencen a dorar agrega la mantequilla y la espinaca; salpimienta.	Salpimienta el tofu y ásalo en una sartén con un poco de aceite de oliva hasta que esté dorado, agrégalo a las verduras.	Integra la pasta, añade la salsa de soya y el aceite de ajonjolí. Sirve y termina con un poco de semillas de ajonjolí negro.	Cuece la pasta hasta que esté suave.	Mientras tanto saltea los espárragos con el ajo, las setas y el aceite de oliva; cuando comiencen a dorar agrega la mantequilla y la espinaca; salpimienta.	Salpimienta el tofu y ásalo en una sartén con un poco de aceite de oliva hasta que esté dorado, agrégalo a las verduras.	Integra la pasta, añade la salsa de soya y el aceite de ajonjolí. Sirve y termina con un poco de semillas de ajonjolí negro.'},
{'Nombre': 'Champiñones con espinaca y ajo', 'Ingredientes': ['8 champiñones grandes','1/2 taza de queso de cabra','1/2 taza de espinaca cocida y picada',	'2 huevos',	'2 dientes de ajo','1 cucharada de mantequilla','1 pizca de nuez moscada'], 'Instrucciones':'Sofríe el ajo con la mantequilla; cuando comience a dorar agrégalo a un tazón y mézclalo con la espinaca, el queso de cabra, el huevo y la nuez moscada. Salpimienta.	Coloca una cucharada sobre los champiñones y hornea durante 10 minutos a 180º C.	Sirve calientes.'},
{'Nombre': 'Cebiche de camarón en jitomate', 'Ingredientes': ['4 jitomates bola', '3 cebollas moradas picada finamente', '1/2 c de pepino picado', '4 tbsp. de cilantro picado', '5 tbsp. de jugo de limón', 'camarón cocido', '1 chile serrano picado', '2 tbsp. de aceite de oliva '], 'Instrucciones':'Mezcla todos los ingredientes excepto el jitomate, y salpimienta.Ahueca los jitomates con cuidado y rellénalos con el cebiche. Llévalos a la mesa. '},
{'Nombre': 'Ensalada de garbanzos y quinoa', 'Ingredientes': ['250g de quinoa', '150g de garbanzos', '100g de guisantes', '1 cebolla', '1 tomate', 'El jugo de 1 limón', '2 ramas de hierbabuena fresca', '1 puñadito de perejil fresco','sal y pimienta','aceite de oliva'], 'Instrucciones':'En una olla a presión, ponemos a calentar a fuego medio una buena cantidad de agua y le añadimos un puñadito de sal. Lavamos y añadimos también los garbanzos, que habrán pasado la noche a remojo junto con un poco de bicarbonato. Dejamos que se cocinen durante 30 minutos, los escurrimos y los dejamos enfriar.	Mientras tanto, en una cazuela con abundante agua, añadimos un par de pizcas de sal y lo calentamos a fuego fuerte hasta que hierva. Añadimos la quinoa lavada y los guisantes, y dejamos que se cocinen aquí durante 15 minutos, removiendo de vez en cuando. Pasado este tiempo, escurrimos todo y lo reservamos.	Montamos la ensalada de garbanzos y quinoa. Después, en una ensaladera amplia, ponemos el tomate y la cebolla cortados en trozos pequeños. Añadimos los garbanzos, la quinoa y los guisantes y lo mezclamos todo.	A continuación, ponemos en un recipiente el jugo del limón, un chorrete de aceite, la hierbabuena y el perejil bien picados. Lo mezclamos bien con un tenedor y se lo echamos por encima a la ensalada. Removemos para que se reparta bien el aliño, y… ¡a servir!'},
{'Nombre': 'Salmon ahumado con aguacate y palitos de cangrejo', 'Ingredientes': ['250g de salmón ahumado en lonchas', '2 aguacates', 'crema de queso', 'palitos de cangrejo o surimi', '500g de espinacas frescas', 'eneldo', 'limón'], 'Instrucciones':'''En primer lugar debemos elegir un salmón ahumado -no marinado-, que se encuentre en lonchas enteras, ya que si lo compramos en trozos nos resultará difícil trabajar con él. Una vez en casa, vamos a abrir la bandeja y dejar que se oxigene durante unos minutos. Mientras tanto podemos ir preparando el resto de los ingredientes.
A continuación vamos a cocer las espinacas. Llenamos dos ollas grandes de agua. A una de ellas le añadimos un puñadito de sal y la llevamos a ebullición. Cuando rompa a hervir añadimos las espinacas. Dejamos que cuezan aproximadamente un minuto y retiramos las mismas a la olla de agua fria. Así cortaremos la cocción de las espinacas y evitaremos que pierdan propiedades  y mantengan el color verde.
Ahora vamos con el aguacate, al que vamos a retirar la pulpa ayudándonos de una cuchara, repasándolo por los bordes y eliminando el hueso central. Cortamos el aguacate en tiras, en forma de bastoncillos y añadimos unas gotitas de limón para dar sabor y evitar que se oxiden. Los reservamos en un plato.
Untamos una loncha de salmón con el la crema de queso. En el lateral por el que empezaremos a enrollar colocamos los bastoncitos de aguacate, junto con un poco de los palitos de cangrejo también en forma de tiras o bastoncillos, un puñado de las espinacas bien escurridas y un poquito de eneldo picado.
Enrollamos con cuidado, procurando que los ingredientes queden juntos en el centro.
Cuando hayamos acabado de hacer todos los rollitos, espolvoreamos con un poco más eneldo.'''},
{'Nombre': 'Alcachofas con almejas', 'Ingredientes': ['500g de alcachofas', '1 cebolla', '4 dientes de ajo', 'perejil fresco', '1 cucharada de harina', '200 ml de vino blanco', '1 cucharada de jugo de limón', '200 g de almejas frescas','sal y pimienta','aceite de oliva'], 'Instrucciones':'''Lavamos y limpiamos las alcachofas. Eliminamos la parte superior fibrosa, el rabillo y todas las hojas demasiado verdes. Nos quedaremos por tanto con el corazón y las hojas más carnosas de la alcachofa. Hecho esto las dividimos en dos mitades y las cocemos en abundante agua hirviendo durante 15 minutos, junto con un puñadito de sal. Cuando estén cocidas, reservamos por un lado las alcachofas y por otro, su caldo.
En una sartén amplia, añadimos un chorro generoso de aceite y lo calentamos a fuego medio. Cuando esté caliente añadimos la cebolla bien picada, salpimentamos y dejamos que se cocine 10 minutos, removiendo de vez en cuando, hasta que se ablande.
Pasado el tiempo añadimos el ajo y el perejil, todo ello bien picado, y lo cocinamos 5 minutos, removiendo con frecuencia.
Hecho esto, añadimos la harina y la mezclamos bien con el resto de los ingredientes. Dejamos que se cocine 3 minutos removiendo constantemente.
Ahora vamos a añadir el vino. Dejamos que se evapore el alcohol durante 2 minutos y lo mezclamos bien. Si crees que la salsa es demasiado densa, puedes añadir un poco del caldo de las alcachofas, hasta conseguir la consistencia deseada, ni demasiado caldosa, ni demasiado densa.
Hecho esto, cortamos en dos partes cada mitad de alcachofa y las añadimos a la sartén junto con el jugo de limón. Salpimentamos y mezclamos bien. Dejamos que se cocinen 5 minutos para que absorban los jugos del resto de ingredientes.
Una vez se cocinen, añadimos las almejas y dejamos que se cocinen 2 minutos. Cuando se abran, mezclamos bien con la salsa, corregimos de sal y pimienta, y la receta estará acabada.'''},
{'Nombre': 'Paella festiva', 'Ingredientes': ['1/8 cucharadita de hilos de azafrán machacados', '2 tazas de caldo de pollo', '1 pimiento (pimentón) rojo, cortado por la mitad a lo largo', '1/4 taza de aderezo italiano fuerte KRAFT Zesty Italian Dressing', '1 lata (14-1/2 oz.) de tomates (jitomates) en cubitos, escurridos', '1/2 taza de cebolla picada', '1/2 taza de cebolla picada', '2 dientes de ajo, bien picados','1 libra de pechuga de pollo deshuesada y sin pellejo, cortada en trozos tamaño bocado', '1/2 libra de salchicha italiana, cortada en trozos de 1 pulgada', '1 paquete (6 oz.) de jamón con miel OSCAR MAYER Honey Ham, picado', '3 rebanadas de tocino (tocineta) OSCAR MAYER Bacon, bien picado', '1 taza de arroz blanco de grano largo de grano largo, sin cocinar', '1 libra de camarones limpios, sin cocer, pelados y desvenados', '12 mejillones, limpios, cepillados y sin barbas', '1 taza de ejotes (habichuelas verdes), descongelados'], 'Instrucciones':'Calienta el horno a 325°F. Mezcla el azafrán con el caldo de pollo; pon a un lado. Corta la mitad del pimiento rojo en tiras; separa. Pica el resto del pimiento. Calienta el aderezo en una sartén grande apta para horno a fuego medio. Incorpora el pimiento picado, los tomates, la cebolla y el ajo; cocina 5 min. o hasta que los pimientos y las cebollas estén tiernos y crujientes, revolviendo frecuentemente. Agrega el pollo, la salchicha, el jamón y el tocino; revuelve. Cocina 10 min., revolviendo frecuentemente. Reduce el fuego a mínimo. Agrega la mezcla de caldo de pollo; mezcla bien. Haz hervir; agrega el arroz y revuelve. Coloca los camarones, los mejillones, los ejotes y las tiras de pimiento rojo sobre el arroz; tápala. Sácala del fuego. Hornea durante 20 min. o hasta que los mejillones se abran y los camarones se vuelvan rosados. Deja reposar 5 min. antes de servir. (Descarta los mejillones que no se hayan abierto).'},
{'Nombre': 'Bacalao a la sartén con ensalada de frijoles blancos', 'Ingredientes': ['1/2 taza de aderezo italiano fuerte KRAFT Zesty Italian Dressing, cantidad dividida','1 cucharadita de páprika ahumada','6 filetes de bacalao fresco (1-1/2 lb)', '2 latas (15.5 oz cada una) de frijoles norteños, enjuagados', '1 tomate (jitomate) grande, sin semillas y picado', '4 cebollitas verdes, en rebanadas finas', '1/4 taza de perejil fresco picado', '1 diente grande de ajo, bien picado', '1/2 taza de aceitunas negras sin hueso, en rebanadas', '3 huevos duros, cortados en cuñas'], 'Instrucciones':'Mezcla 1/4 taza de aderezo con la páprika; vierte la mezcla sobre el pescado en un plato llano. Voltea el pescado para cubrir parejamente por ambos lados cada filete. Ponlos a marinar en la nevera durante 30 min. Mezcla los ingredientes restantes, entretanto, excepto las aceitunas y los huevos, en un tazón grande. Saca el pescado de la marinada y deshazte de ésta. Cocina el pescado en una sartén grande a fuego medio-alto de 4 a 5 min. por lado o hasta que el pescado se desmenuce fácilmente con un tenedor. Sírvelo con la ensalada de frijoles; corona todo con las aceitunas y los huevos.'},
{'Nombre': 'Gambas a la plancha', 'Ingredientes': ['Gamba blanca o roja, grande, de calidad', 'Papel de hornear recortado a medida de la plancha', 'Aceite de oliva virgen extra un chorrito', 'Sal gruesa abundante'], 'Instrucciones':'Comenzamos recortando un papel de hornear, de la medida de la plancha en que vayamos a cocinar las gambas. Después haremos las gambas a la plancha sobre este papel, que deja pasar perfectamente el calor pero protege a la plancha de olores, líquidos y evita que se peguen los alimentos. Sobre el papel, colocamos las gambas, todas alineadas y mirando en la misma dirección. Así, cuando les demos la vuelta a mitad de la cocción tendremos claro a las que ya hemos dado la vuelta, evitando que alguna se haga solo por un lado. En la zona donde la cabeza y el cuerpo de la gamba se juntan, ponemos unos granillos de sal gruesa, como podéis ver en el collage de más abajo. Después, añadimos un chorrito o hilo de aceite de oliva virgen extra y dejamos que se cocinen, a fuego máximo, durante dos minutos. Pasado ese tiempo, damos la vuelta a las gambas con unas pinzas, y dejamos que se cocinen por el otro lado otro minuto o dos minutos más, dependiendo del calibre y grosor de las gambas, sacándolas a una fuente y degustándolas inmediatamente. Sobre la plancha, quedará el papel de hornear manchado, que podemos arrugar y tirar, quedando la plancha limpia y lista para el siguiente uso.'},
{'Nombre': 'Cookies de avena, plátano y almendras', 'Ingredientes': ['100 gramos de avena', '2 plátanos medianos', '30 gramos de almendras', 'canela'], 'Instrucciones':'Para comenzar a elaborar estas cookies simplemente debemos colocar en un recipiente la avena y los plátanos en trozos grandes. Con un tenedor comenzamos a pisar los plátanos mientras los unimos con la avena. Cuando estos ingredientes están unidos agregamos las almendras picadas groseramente y si deseamos, una cucharadita de canela. En esta ocasión no hemos añadido azúcar, pero si se desea se puede agregar una cucharada de miel, aunque no lo considero necesario. En una placa para horno antiadherente colocamos con ayuda de una cuchara las cookies y les damos forma redonda hasta dejarlas finas. Precalentamos el horno fuerte y horneamos por 15 a 20 minutos.'},
{'Nombre': 'Barritas fitness de avena y frutos secos', 'Ingredientes': ['Higos secos o deshidratados', 'Zumo de naranja recién exprimido', 'Estevia líquida', 'Copos de avena', 'Coco rallado', 'Almendras', 'Nueces', 'Agua cantidad necesaria'], 'Instrucciones':'Para elaborar estas barritas fitness comenzaremos colocando en una batidora o en el vaso de un motor de cocina los higos secos junto a la stevia líquida y el zumo de dos gajos de naranja (aproximadamente 4 cucharadas). Accionamos el motor y procesamos hasta obtener una pasta consistente pero húmeda, si fuera necesario agregamos agua poco a poco de a cucharadas hasta obtener una pasta de higos. En un bol mezclamos los higos con todos los ingredientes secos: los copos de avena (yo los procesé un poco para que queden más pequeños), el coco rallado, las nueces picadas groseramente y las almendras partidas por la mitad. En este punto se puede agregar más agua si fuese necesario o más edulcorante si habiendo probado nos parece que falta dulzor. Unimos todos los ingredientes con ayuda de una cuchara o usando las manos para lograrlo y en un recipiente rectangular colocamos la preparación, aplanando la misma y extendiendo hasta que alcance un centímetro de grosor. Marcamos las barritas (rectangulares o cuadradas) y las llevamos al refrigerador por una hora. Pasado dicho tiempo las barritas estarán firmes, consistentes y crocantes. Desmoldamos y listas para consumir.'},
{'Nombre': 'Brochetas de cerdo marinadas con salsa de maní', 'Ingredientes': ['25 palos de bambú','600 gr de solomillo de cerdo','1 diente de ajo picado fino',	'1 vara de lemongrass picada fina',	'1 cucharadita de ralladura de limón',	'1/2 cucharadita de semillas de cilantro machacadas',	'3 cucharadas de salsa de ostras',	'2 cucharadas de vinagre',	'3 cucharadas de aceite de oliva',	'1/2 taza (120 ml) de salsa de soya','1 cucharada de mantequilla',	'1/2 cucharada de pimienta negra entera	Para la Salsa de Maní','2 cucharadas de mantequilla de maní',	'1 cucharada de vinagre blanco',	'1/4 cucharada de paprika o pimentón molido',	'2 cucharadas de crema	Sal y pimienta'	], 'Instrucciones':'1.Prepare las brochetas. En los palos de bambú inserte las láminas de cerdo hasta completar los 25 palos. Coloque en una fuente y reserve.		2. Prepare la marinada. En un bol coloque todos los ingredientes de la marinada, excepto la mantequilla y la pimienta. Mezcle bien y luego vierta sobre la fuente con las brochetas. Tape con un papel plástico y refrigere por 3 horas.		3. Retire las brochetas de la fuente y estile. Reserve la marinada. En una sartén coloque la mantequilla y los granos de pimienta; caliente a fuego medio y agregue las brochetas. Cocine hasta que las brochetas estén cocidas y doradas. Retire del fuego y conserve el calor.		4. Prepare la salsa de maní. En la misma sartén coloque 2/3 de agua fría, mantequilla de maní, vinagre, paprika, crema y la marinada reservada. Cocine revolviendo, hasta calentar y sazone con sal y pimienta. Retire del fuego y sirva de inmediato junto con las brochetas de cerdo.'},
{'Nombre': 'Crema de mariscos', 'Ingredientes': ['1 puerro''1 pimiento rojo','1 cebolla''300 g de langostinos','1 kg de mejillones cocidos','2 patas grandes de pulpo','1 cda. de pimentón','1 ½ de caldo de pescado','100 mL de crema'], 'Instrucciones':'Corta en trozos el poro, la cebolla y el pimiento rojo. Agrega los langostinos enteros, los mejillones ya cocidos y el pulpo. Remueve y agrega una cucharada de pimentón. Agrega el caldo de pescado y cocina a fuego lento durante unos 25 a 30 minutos. Retira la cáscara de los langostinos y pasa por la batidora o licuadora. Cuela la mezcla para que quede una crema muy fina. Incorpora la crema y sazona con sal al gusto.'},

>>>>>>> 66c672beccfd679eff6062008dc5cf877d7eb78c

]



#https://drive.google.com/file/d/1xKDzb3cBpYFZIoLxPCsoc5C4OzDqPetr/view?usp=sharing
#https://drive.google.com/uc?id=1xKDzb3cBpYFZIoLxPCsoc5C4OzDqPetr


alergiasData = {'Mariscos': ['camaron, cangrejo','almeja','pulpo','langostinos'],'Lácteos':['leche','queso'],
'Gluten':['trigo', 'avena', 'cebada', 'centeno']} #alimentos en 

ingredientes_recetas = set()
for receta in recetas:
  if receta["img_url"] != "":
    receta["img_url"] = receta["img_url"].replace("file/d/","uc?id=")
    receta["img_url"] = receta["img_url"].replace("/view?usp=sharing","")

  for ingrediente in receta['Ingredientes']:
    ingredientes_recetas.add(ingrediente)
